### ISSUE TITLE
Focus ring looks a bit broken

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-header#116]
Sometimes the browser's default focus effect (on Mac at least) doesn't align well with the design:

when tabbing to the search input:
![image](https://cloud.githubusercontent.com/assets/250617/12515671/611caef0-c121-11e5-8044-9fa3efbde4ba.png)

after clicking search icon, while transitioning:
![image](https://cloud.githubusercontent.com/assets/250617/12515687/6cc9a172-c121-11e5-81bd-1bccfc25b5de.png)

bottom cut off:
![image](https://cloud.githubusercontent.com/assets/250617/12515961/de9f3e00-c122-11e5-8a8c-e6911fd76e7a.png)

partially cut off:
![image](https://cloud.githubusercontent.com/assets/250617/12515977/f45a9c62-c122-11e5-9424-12cab11926ac.png)

Suggest unsetting the default focus ring, and replace it with some custom `:focus` styles

**Comment by alicebartlett** [comment]
https://github.com/Financial-Times/o-header/pull/164 Fixes this
