### ISSUE TITLE
Mobile/Tablet-sized header does not display Next 'user account' links with JS off

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/o-header#130]
In Next site, the user account-related links: "myFT", "sign out"/"sign in", "My account"/"subscribe" are not displayed when JS is switched off.

Next Jira defect: https://jira.ft.com/browse/NFT-267

**Comment by AlbertoElias** [comment]
This isn't a header issue, but a next footer issue as in core experience, the header just limits itself to pointing to the footer

**Comment by tgabe** [comment]
Thanks, @AlbertoElias !
