### ISSUE TITLE
In Opera mobile, header height is high

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/o-header#132]
In Chrome Mobile v35:

![operamobile_v35_2016-02-22-17-00-38](https://cloud.githubusercontent.com/assets/14106759/13226095/b1edb1fc-d987-11e5-8e00-19810939c64d.png)

I'd classify this as **low priority** due to the low number of users in Next users as of Jan 2016: 
Subscribers - 43
All cohorts - 1,867

Next defect link: https://jira.ft.com/browse/NFT-164

**Comment by onishiweb** [comment]
Fixed now.
