### ISSUE TITLE
Search icon linking to incorrect search box id

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/o-header#133]
i.e. `#header-search`, should be `#o-footer__search-term`

https://jira.ft.com/browse/NFT-335

**Comment by AlbertoElias** [comment]
If it's an error in the latest v5 branch, that's just a demo thing, so it's not relevant. If it's a next branch error, then next is maintaining that

**Comment by ironsidevsquincy** [comment]
Someone has updated the search box id in the footer without updating the header search icon link. Who should I talk to about this so it doesn't happen again?

**Comment by AlbertoElias** [comment]
I think the footer next is using is under the next branch, so this is all a next thing. It's an implementation issue, so it's up to each team to sort that kind of thing out

**Comment by ironsidevsquincy** [comment]
fixed in https://github.com/Financial-Times/o-header/commit/c7f0f0c134d81e258916b164d6bda8ba114c2a66
