### ISSUE TITLE
Mobile sign in / subscribe links

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-header#138]
![image](https://cloud.githubusercontent.com/assets/447559/13567924/1000d3a4-e456-11e5-8019-133c50a675dd.png)

code here https://github.com/Financial-Times/n-header-footer/blame/abf5875a6ae4ecd26c1f757869dfbb72fdf40803/templates/partials/membership-mobile-promotion.html

**Comment by AlbertoElias** [comment]
Implemented in #144

**Comment by AlbertoElias** [comment]
Released in beta 8
