### ISSUE TITLE
Links flush against bottom of header

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#147]
Missing space between links and bottom of header (although this does allow the 'Home' link's highlighted background to be hidden when the search bar is opened).

Browsers: Chrome (v49.0.2623.87); Firefox (v44.0.2); Safari (9.0.3); IE9-11

N.B. On Safari (v44.0.2) the header height is shorter.

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13951051/7befc40e-f026-11e5-8aa6-5d3822af2263.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13951053/7ec0f982-f026-11e5-89fa-f23d53a2b29c.png)

**Comment by AlbertoElias** [comment]
Yes, I did this on purpose thinking the current one was a bug as it looked really awkward with the search bar open
