### ISSUE TITLE
Alignment of 'Financial Times' home link

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#148]
Title link veers slightly to the left; its margin extends to the far left of the header while the current implementation's margin only reaches a point aligning with the left side of the hamburger.

Browsers: Chrome (v49.0.2623.87); Firefox (v44.0.2); Safari (9.0.3); IE9-11

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13951160/05e1eac0-f027-11e5-9e5d-ceba30e89fbd.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13951163/08479224-f027-11e5-948e-3d9b32cfb6df.png)

**Comment by AlbertoElias** [comment]
Isn't the beta correct here as it has aligned the hamburger icon and the edition switch?

**Comment by AlbertoElias** [comment]
Work in next beta should fix this

**Comment by AlbertoElias** [comment]
Fixed in beta 10
