### ISSUE TITLE
Alignment of nav items (Subnav/Home/World/UK/Companies, etc.)

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#149]
Nav items veer to the right.

Browsers: Chrome (v49.0.2623.87); Firefox (v44.0.2); Safari (9.0.3); IE9-11

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13951308/fdee24e0-f027-11e5-89d4-a53d58dbc570.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13951312/034c0f10-f028-11e5-87a0-d9dc6870f0cd.png)

**Comment by AlbertoElias** [comment]
Isn't the beta correct here?
