### ISSUE TITLE
Subnav in M+ layout

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#151]
- [ ] Far left of Top Stories section not covered when subnav opened; likely relates to position of hamburger icon, which is further left in current.
- [ ] When opening subnav, other nav links (Home/World/UK, etc.) shift to the left.
- [ ] Font sizes smaller than current.
- [ ] z-index issues (quick fix (for front-page) would be `z-index: 2`; poss. better in long run to start employing https://github.com/Financial-Times/next-sass-setup/blob/58466d840edbc4fda2bf6dae1eaa1ca95920f08c/_z-indexes.scss).

Browsers: Chrome (v49.0.2623.87); Firefox (v44.0.2); Safari (9.0.3); IE9-11

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13951604/00f2f4ca-f02a-11e5-8bb0-a33e5b015adc.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13951608/065efb7a-f02a-11e5-850a-aa820faad49a.png)

**Comment by AlbertoElias** [comment]
1. Fixed in next beta
2. Need to fix in next beta
3. Fixed in next beta
4. Next beta plus Next using new o-header-z-index Sass variable will fix

Will close when next beta is released

**Comment by AlbertoElias** [comment]
Fixed in beta 10
