### ISSUE TITLE
Size of myFT/Sign Out/My Account / myFT/Sign In/Subscribe links

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#152]
Larger font size used than in current.

Browsers: Chrome (v49.0.2623.87); Firefox (v44.0.2); Safari (9.0.3); IE9-11

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13951779/dafaf14a-f02a-11e5-94c6-755a33741aa8.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13951784/dd3403f2-f02a-11e5-8dd7-451eb94d2007.png)

**Comment by AlbertoElias** [comment]
Fixed in beta 10
