### ISSUE TITLE
'Financial Times' home link on IE9-11

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#154]
Far right of 's' in 'Financial Times' appears cut off; although current version also displays this oddly.

##### Current live
![screen shot 2016-03-22 at 15 29 48](https://cloud.githubusercontent.com/assets/10484515/13957100/27fb92de-f043-11e5-8c1d-3578527b9cbd.png)

##### v.5.0.0-beta.9
![ie9-11](https://cloud.githubusercontent.com/assets/10484515/13956985/bb02ea4c-f042-11e5-95e1-a1aa17e11c60.png)

**Comment by AlbertoElias** [comment]
Those browsers will be using the svg, right?
