### ISSUE TITLE
IE8

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#155]
- [ ] Hamburger further to the left and higher.
- [ ] Loupe further to the right and higher.
- [ ] 'Financial Times' home link much smaller.
- [ ] myFT/Sign Out/My Account / myFT/Sign In/Subscribe links further right, lower down and larger font size.
- [ ] Header height is shorter.

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13957175/774f3048-f043-11e5-9c83-6ff13c1c2d63.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13957191/89924736-f043-11e5-94e6-991e981de7de.png)

**Comment by AlbertoElias** [comment]
I think you're getting a very different behaviour than what I get, so would be good to take a look in person

**Comment by AlbertoElias** [comment]
Found the fix in Next
