### ISSUE TITLE
On narrow-ish tablet meganav layout breaks

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-header#163]
![image](https://cloud.githubusercontent.com/assets/447559/14346764/87fbb1f4-fcab-11e5-810c-3f25e2fd177c.png)

**Comment by AlbertoElias** [comment]
@wheresrhys what width so I can replicate? It doesn't happen to me resizing chrome on next

**Comment by wheresrhys** [comment]
To recreate use dev tools to remove 'transport' from the 'Companies' list i the next nav. You'll See that it's broken at most widths because the second row of submenus doesn't properly clear the first

**Comment by AlbertoElias** [comment]
Fixed in #167
