### ISSUE TITLE
Needs text fallbacks for slow connections

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-header#166]
e.g. this can happen https://financialtimes.slack.com/archives/ft-next-support/p1461053822000074
![image](https://cloud.githubusercontent.com/assets/447559/14632354/0db0e07c-0610-11e6-9d76-b00d64c2fb52.png)

**Comment by gvonkoss** [comment]
Closing as this does not seem to be relevant to the last major release and the changes in it.
