### ISSUE TITLE
Menu displays off-page on firefox <28

### ISSUE THREAD

**Issue by laurieboyes** [Financial-Times/o-header#170]
![screen shot 2016-04-21 at 11 30 18](https://cloud.githubusercontent.com/assets/4622378/14706108/aee7f82c-07b4-11e6-9733-574c8b47c575.png)

The menu is arranged using o-grid, which relies on `flex-wrap` property (https://github.com/Financial-Times/o-grid/blob/e061d067aa5398e029e8e424e20bb5d6bc46aa65/src/scss/_main.scss#L474), which isn't supported in firefox <28.

One solution is to add `flex-direction: column` to the header inner (here: https://github.com/Financial-Times/o-header/blob/d6a2795e3fe8f95d1c8bfd5173d5811c2e60d79b/src/scss/_base.scss#L27-L29)

However, this might reasonably be construed as a nasty hack (?). Do we have a strategy in place for covering for old firefox's flexbox shortcomings?

**Comment by alicebartlett** [comment]
We (the FT) does have a policy-ish for this which is that browsers whose visits form less than 0.1% of visits are considered "unsupported" (unless there is a strategic reason for supporting them). This metric is based on visits from individual browsers though, and while no quantity of visits from a single version of FF exceeded 0.1%, when you group all of them, the total for December is above the threshold.

For the month of December, 0.4% of visits to the ft.com were from browsers flagged as Firefox < 29.
I think this means we should try and fix this, particularly as this layout bug is now majorly impacting the layout of the whole homepage.

**Comment by alicebartlett** [comment]
Actually! My mistake. This problem is fixed with the latest major of o-header (now quite old).
Investigating this has led me to find some other rather broken behaviour on the homepage which I'll raise elsewhere.
