### ISSUE TITLE
Broken `tint` parameter in Image Service URLs

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/o-header#195]
I'm not very familiar with the `tint` parameter in the Image Service, but I found that it was applied as expected in o-header. Changing the desired tint to `#ff0000` for clarity, I don't see it with the URL as output by o-header (https://image.webservices.ft.com/v1/images/raw/ftlogo:brand-ft-masthead?source=o-header&tint=#ff0000,#ff0000&format=svg), but I do with the `#`s removed: https://image.webservices.ft.com/v1/images/raw/ftlogo:brand-ft-masthead?source=o-header&tint=ff0000,ff0000&format=svg.

cc @alicebartlett, @i-like-robots

**Comment by i-like-robots** [comment]
Implementation here: https://github.com/Financial-Times/o-header/blob/master/src/scss/_mixins.scss#L87-L90

I believe this was copied over from o-icons, here: https://github.com/Financial-Times/o-icons/blob/master/scss/_mixins.scss#L19-L20

**Comment by georgecrawford** [comment]
Is the `\9` in https://github.com/Financial-Times/o-header/blob/c724ea028f5ddd7eeaecc28405a751af83ba488b/src/scss/_mixins.scss#L74 a typo? Assume so.

**Comment by georgecrawford** [comment]
My problem was with a CSS minifier, so I'm going to close this.
