### ISSUE TITLE
Edition switcher does the opposite of what most people think

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/o-header#201]
I asked ten people in the next team to answer this question:

"Are you on the UK edition or the International edition?" 

![image](https://cloud.githubusercontent.com/assets/224547/17215195/fd9382a4-54d3-11e6-94e2-6964510f94bf.png)

Nine out of ten people said that it's on the International edition, because you can click to the UK Edition.

Guess what? Nine out of ten people get it wrong.

![image](https://cloud.githubusercontent.com/assets/224547/17215150/d159eca0-54d3-11e6-9205-bb84eea163d2.png)

Surprise! You're on the UK Edition!

-----------------------------------

The immediate fix would be to swap the link color and underline effect from whatever version it is now to the other version.

**Comment by i-like-robots** [comment]
Maybe registry.origami.ft.com/components/o-buttons#demo-grouped

**Comment by adambraimbridge** [comment]
Sounds good to me 👍

**Comment by AlbertoElias** [comment]
Styling for this in #202
