### ISSUE TITLE
Prevent drawer closing when right-clicked

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/o-header#222]
Drawer closes when right-clicked on and leaves an odd experience:

![menu-bug](https://cloud.githubusercontent.com/assets/1240073/19120317/53acfb3a-8b1a-11e6-8642-4a21b9c4b3ef.gif)

**Comment by alicebartlett** [comment]
This behaviour is caused by the mouse "leaving" the drawer. We want this so that to close the drawer the user can move their mouse out of it.

A sensible fix might be to change this behaviour so that the user has to change the actual focus or click the "X" button to close the drawer.
