### ISSUE TITLE
Contrast of fancy links

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/o-header#233]
I tried to do this one but it turned into a bit of a rabbit hole for me and I stopped here https://github.com/Financial-Times/o-header/blob/056400381d87b5fe884825c316762bea6370b3bf/src/scss/_mixins.scss#L62-L65

<img width="129" alt="screen shot 2016-12-18 at 07 52 31" src="https://cloud.githubusercontent.com/assets/3425322/21292326/201ba5dc-c4f9-11e6-96a9-d0e0e927b845.png">

What I wanted to change was the `#999999` in the hover state of the fancy link for `#727272`, because `#999999` on a `#fdf8f2` background fails contrast checks (even more so when the opacity is reduced for the lighter stripes). `#727272` makes it over the 4.5:1 threshold (for the dark stripes anyway).

DAC's feedback on the fancy links was that both the teal one or the grey one fail contrast checks, because of the lighter stripes, and that a solid underline would be better. I will try to get us a pass by having at least the dark stripes on both be over 4.5:1.

![teal](https://cloud.githubusercontent.com/assets/3425322/21292350/f5527c9e-c4f9-11e6-8901-023d933cb607.png)

#999999
<img width="64" alt="screen shot 2016-12-18 at 08 17 32" src="https://cloud.githubusercontent.com/assets/3425322/21292367/819fba86-c4fa-11e6-803e-fd337b308b84.png">

#727272
<img width="68" alt="screen shot 2016-12-18 at 08 17 19" src="https://cloud.githubusercontent.com/assets/3425322/21292366/819cf17a-c4fa-11e6-8db9-9bf43276b99f.png">

cc @onishiweb @i-like-robots

**Comment by alicebartlett** [comment]
Thanks for trying to resolve this with darker contrast. I have some additional information here which is that we're phasing out the pinstripes in favour of solid lines _anyway_.

**Comment by lc512k** [comment]
Great to hear. Thanks @alicebartlett!
