### ISSUE TITLE
Remove background tint on nav at smaller breakpoints

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-header#264]
For consistency please can we remove the tint that is appearing on the nav at mobile breakpoints. So it goes from this (current):

<img width="733" alt="screen shot 2017-09-25 at 15 09 54" src="https://user-images.githubusercontent.com/11214093/30813313-018ea396-a205-11e7-9e27-621fbc636f84.png">

To just the ordinary pink (Paper)
<img width="731" alt="screen shot 2017-09-25 at 15 10 03" src="https://user-images.githubusercontent.com/11214093/30813316-035aa6a2-a205-11e7-86db-eedc674d26d7.png">

**Comment by notlee** [comment]
I've released this as part of v7.1.0.
https://github.com/Financial-Times/o-header/releases/tag/v7.1.0
