### ISSUE TITLE
Weird clipping of Financial Times in Edge

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-header#276]
The masthead is currently being impacted by this bug in MS edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4705340/

It would be great if we could find a workaround to this problem, however a cursory google has not turned up much.

This problem is worse when the browser is slightly zoomed, but can be replicated in browser stack at any zoom (just to a lesser extent)

![image002](https://user-images.githubusercontent.com/68009/33878867-90d1a48e-df24-11e7-83a2-07cc18436cdc.jpg)

**Comment by JakeChampion** [comment]
Fixed via #277
