### ISSUE TITLE
Transparent header is incomplete

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-header#284]
We can't find any examples of it being used across any products, but the drawer is missing transparent treatment.

**Comment by notlee** [comment]
This is used by the data journalism team, see [g-components](https://github.com/Financial-Times/g-components/blob/efd41ad4b97c4a74867e49c3877a9b1fe19f5786/src/header/index.js#L16), for [pages such as this](https://ig.ft.com/gb-broadband-speed-map/). They don't use the nav elements. Let's update the demo and docs to reflect the current limitations of the transparent theme. Perhaps we shouldn't add support for other nav items until there's a user need for it.

**Comment by notlee** [comment]
Also hi Gabi! Miss you!

**Comment by notlee** [comment]
I've [asked in the design-ops channel](https://financialtimes.slack.com/archives/C01481FKWA2/p1600870610003200) if there are any known usecases for a transparent drawer and will reopen this issue if there are
