### ISSUE TITLE
Design update to nav to make it more consistent.

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-header#286]
These changes are to the nav and sub nav at larger sizes (before the tablet/mobile deeper version kicks in). They are mainly to increase the font size of the sub nav while not changing the overall height of the header unit (to avoid a breaking change). 

**Main Nav changes:**
~- Items in the main nav now have a 16px gap between each list item. This is improves click-ability especially when two letter menu items are being selected (eg. UK or US).~
~- The height the main nav bar is reduced to 36px (not including the 1px rule).~
- Secondary menu items (e.g Portfolio) remain right aligned and in Sentence case but are now in Metric Semibold. 

**Sub nav changes:**
~- The sub nav height has been increased to 36px (now the same as main nav)~
~- The text size has gone up to 16px and is now consistent with the mobile (and tablet) nav type sizes.~

Any questions then do let me know. 

_Sketch file is here (page 2):_
https://drive.google.com/file/d/0B8f0KVx7ey79bWgtV3FFbkxnNVE/view

New proposed design:
![o-header tweaks desktop](https://user-images.githubusercontent.com/11214093/37838978-38d62fd4-2eb1-11e8-8584-9650d65e5670.png)

**Comment by notlee** [comment]
Closing as a stale issue and James is no longer at the FT 😢 There have been PRs since this issue to update font size.
