### ISSUE TITLE
Question around myFT logo in the header. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-header#296]
The myFT logo has been implemented as 52px wide but within a 40x40px container which is meaning our tooltip arrow is appearing off centred. Not super important but would be nice to address this. 

![image 1](https://user-images.githubusercontent.com/11214093/38569741-0276c3fe-3ce4-11e8-93fb-6f4b15e91730.png)

**Comment by notlee** [comment]
Closing as this is a stale issue. Although it may have been fixed by https://github.com/Financial-Times/o-tooltip/pull/61, as the tooltip could position itself center without being contained to the right of the myft logo.
