### ISSUE TITLE
o-ft-icons dependency conflict causes header build failure

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-header#30]
http://build.origami.ft.com/bundles/js?modules=o-ft-header

```
Cannot complete build: Unable to find suitable version for o-ft-icons

o-ft-icons ^1.2.3 required by o-ft-header 2.3.0
o-ft-icons 2.0.0 required by o-hierarchical-nav 0.2.4
```

**Comment by kaelig** [comment]
Looks like it hasn't popped up in a while, so I'll be closing this issue. For what it's worth, I've pinged the bower team on the issue linked by Andrew.
