### ISSUE TITLE
Require $system_code variable be set by consumers of this component

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-header#312]
We have a lot of origami-image-service requests with source=o-icons, which is actually not useful as we don't know who the real source is. E.G. Is it HTSI/FT/NAR/ScoutAsia?

This is due to the fact that the origami components hardcode a source value in their scss. E.G. https://github.com/Financial-Times/o-header/blob/664633bf79aff582b5b7676f79b02399dc18d082/src/scss/_mixins.scss#L118

I'm thinking when we introduce source= to the Origami-Build-Service, we update the origami components to require users pass in a $source or $system_code variable in order to use them. We can then use the $system_code/$source as the value passed to the origami-image-service URLs within the scss.

Waiting on Financial-Times/origami-build-service#67

**Comment by notlee** [comment]
Duplicate. To be completed as part of the major cascade https://github.com/Financial-Times/o-header/issues/343
