### ISSUE TITLE
Scroll buttons not showing on subnav

### ISSUE THREAD

**Issue by liamkeaton** [Financial-Times/o-header#313]
On the https://www.ft.com/columnists page it's been noticed that the right scroll button is not being shown even though there are items to scroll. They do however show once you start scrolling.

![image_ 1](https://user-images.githubusercontent.com/1721150/45696346-53f84e00-bb5b-11e8-84ec-81507b55b831.png)

**Comment by gvonkoss** [comment]
Fixed based on ☝️
