### ISSUE TITLE
Spacing and type adjustments

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-header#321]
The primary navigation and user navigation needs tweaking temporarily while we work out how we limit the number of new items being added. I've spoken with Simon Coxon and we agreed that the best compromise is to change it so that...

**Spacing between primary nav items:**
```diff
- 14px
+ 12px
```

**Type size of primary nav items:**
```diff
- 16px (type scale 0)
+ 14px (type scale -1)
````

Originally a font size of `15px` and a spacing of `8px` was suggested by Simon as this was the smallest change in size which could be accommodated. However `15px` is not in [the scale provided by o-typography](https://github.com/Financial-Times/o-typography#usage), so setting the type to this size would introduce technical and design debt. Also `8px` spacing between items looked visibly more condensed.

After some discussion we decided on a value of `14px` with `12px` spacing because the ratio is roughly the same and both values are achievable using o-typography mixins.

**Comment by rowanmanning** [comment]
Update on this: we've been told by product to hold fire, we shouldn't be fixing the issue on our end.

**Comment by notlee** [comment]
Another update on this: we've been told not to hold fire, and have fixed this on our end. https://github.com/Financial-Times/o-header/pull/322
