### ISSUE TITLE
subnav wrap-outsize margin isn't building correctly

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-header#339]
I _think_ this (#336)  is causing a bug on the preferences pages.

![image](https://user-images.githubusercontent.com/51677/60445907-20813e80-9c18-11e9-8ebb-5ec3af329b23.png)

> https://www.ft.com/preferences/privacy

This seems to get built into the following in our head CSS.

```css
.o-header__subnav-wrap-outside {
  margin:-5px
}
```

![image](https://user-images.githubusercontent.com/51677/60446007-558d9100-9c18-11e9-956d-861d02569428.png)

Any ideas?

_Originally posted by @sjparkinson in https://github.com/Financial-Times/o-header/pull/336#issuecomment-507298560_

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/o-header/pull/336#issuecomment-507299044

**Comment by notlee** [comment]
Hopefully 7.8.10 works around this https://github.com/Financial-Times/o-header/pull/340. I'll leave the issue open until we can confirm.

**Comment by sjparkinson** [comment]
![image](https://user-images.githubusercontent.com/51677/60501062-4c9dcd80-9cb3-11e9-9b9c-38b2720be7d9.png)

Happy to confirm it resolves the issue.
