### ISSUE TITLE
Sticky header overflows screen width on small devices

### ISSUE THREAD

**Issue by AniaMakes** [Financial-Times/o-header#360]
This is a bug report.

This issue arises when testing the website in up-to-date Chrome (MacOS Mojave) using dev tools' device toolbar (simulate small screens).
The issue is especially noticeable in the smallest screen (iPhone 5 / SE) (320px), and to the lesser degree on the iPhone 6/7/8 (375px). 
Exploring elements in devtools suggests that the header has a computed width of 394px. The trigger is
```
.o-header--sticky {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 99;
    transform: translateY(-100%);
    transition: transform .35s cubic-bezier(1,0,.5,1.275);
    will-change: transform;
    border-top: 30px solid transparent;
    margin-top: -30px;
}
```  

This bug does not appear on the demo page for the sticky header in the origami registry, however the demo page has "my FT" logo and the sticky header in my app has "Sign in" and "Subscribe" buttons instead. 

I suspect that the issue might be that the header needs to fit all its blocks in a single line and due to the size of each block the header can't get smaller than 394px. 

**Screenshots**
iPhone 6/7/8 - the white background is 100% of the screen width. You can see a faint cream strip on the right hand side - that's the overflow area and if you follow the strip up you can see that the header is the culprit fr the overflow. 
![Screenshot 2020-02-05 at 09 16 14](https://user-images.githubusercontent.com/31079643/73829968-c4a91480-47fb-11ea-9e04-8ccaf82693ec.png)

iPhone 5/SE - as above, the white background is 100% of the screen width. The cream strip on the right hand side is very clear here. 
![Screenshot 2020-02-05 at 09 16 35](https://user-images.githubusercontent.com/31079643/73830954-6e3cd580-47fd-11ea-84f4-1ca5ba7fa607.png)

iPhone 5/SE - different view (it seems to be random if this or the previous view gets shown). Here you don't have the cream strip, but the floating header is clearly cut off - and you only get a part of the Subscribe button. 
![Screenshot 2020-02-05 at 09 14 53](https://user-images.githubusercontent.com/31079643/73831021-8c0a3a80-47fd-11ea-9025-5398ea2463d6.png)

**Comment by notlee** [comment]
hey, what app are you working on? I would expect those links to be in the nav like on the front page of ft.com.

E.g. signin and subscribe in the nav:
![desktop](https://user-images.githubusercontent.com/10405691/73847511-56c21480-481e-11ea-888f-7abbfa3060bd.png)

And on mobile there are separate links above the header:
![mobile](https://user-images.githubusercontent.com/10405691/73847616-912bb180-481e-11ea-85a1-7d7ba13a52e3.png)

**Comment by AniaMakes** [comment]
@notlee I'm working on next-profile

**Comment by notlee** [comment]
Looking at existing examples those links usually go in the navigation. If you're working from a design where they are in the header instead query why, if it's intentional let us know and we'll discuss any header changes that might be needed. 😊 

But if this is for a profile page, aren't users already subscribed / signed in at that?

**Comment by AniaMakes** [comment]
> But if this is for a profile page, aren't users already subscribed / signed in at that point?

Hm... good point. For some reason - maybe because I'm using a dummy account - it's not treating me as logged in (I can't read articles, for example). I'm going to assume it's not an issue with Origami and ask within my team to see if anyone can figure out why this is happening. 

Thank you for your help!

**Comment by notlee** [comment]
No problem! I'll close this for now but feel free to reopen
