### ISSUE TITLE
Drawer menu vertical scrollbar partially obscures active elements

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-header#365]
## What

The scrollbar is laid over the menu expansion triggers, which makes them harder to see and select.

## Details

Tested URL: https://www.ft.com/__origami/service/build/v2/demos/o-header@8.0.2/header?brand=master
Browser: IE11 on Windows 10

![image](https://user-images.githubusercontent.com/1115667/77420971-4d3f3c80-6dcb-11ea-85c1-a06b1e2d2217.png)

**Comment by notlee** [comment]
thanks, we updated this behavior

**Comment by petrklus** [comment]
Thank you @notlee - would this be back ported to v7 branch as well or is it already implemented in both?

**Comment by notlee** [comment]
Hey @petrklus, as this is small I'm happy to backport to v7 (will reopen this issue)

**Comment by notlee** [comment]
Done, that's released in v7.8.13 :)
