### ISSUE TITLE
Improve accessibility of the 'link buttons'

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-header#380]
## What
Currently we are not following the WAI-ARIA guidelines for role=button fully.

<p><strong>Note</strong>: If using role="button" instead of the semantic <code>&lt;button&gt;</code> or <code>&lt;input type="button"&gt;</code> elements, you will need to make the element focusable and have to define event handlers for <code><a href="/en-US/docs/Web/Events/click" title="/en-US/docs/Web/Events/click">click</a></code> and <code><a href="/en-US/docs/Web/Events/keydown" title="/en-US/docs/Web/Events/keydown">keydown</a></code> events, including the <kbd>Enter</kbd> and <kbd>Space</kbd> keys, in order to process the user's input. See the <a class="external" href="https://www.w3.org/TR/wai-aria-practices/examples/button/button.html" rel="noopener">official WAI-ARIA example code</a>.</p>

We need to add the <code><a href="/en-US/docs/Web/Events/keydown" title="/en-US/docs/Web/Events/keydown">keydown</a></code> event listener and listen for the <kbd>Enter</kbd> and <kbd>Space</kbd> keys being pressed.

Or we need to use a `<button>` instead!

**Comment by nickcolley** [comment]
@JakeChampion thanks for writing this up.

Next steps for me will be to:

1. find the places we use role=button in origami.
2. See if we can use a button instead
3. For places where we cannot use a button, add functionality missing
4. (Optional) Consider a broader polyfill that identifies role=button anywhere.

**Comment by JakeChampion** [comment]
@nickcolley I will get the answer to step 1 for you as I have all the origami repositories available on my machine :-)

Here is the answer to step 1
```
o-header-services/MIGRATION.md
o-ft-buttons/demos/test.html
origami-website/_includes/header.html
o-ft-buttons/demos/src/test.mustache
origami-registry-ui/views/partials/header.html
origami-repo-data/views/partials/header.html
origami-screencap-service/views/partials/header.html
o-buttons/demos/src/test.mustache
o-header-services/test/helpers/fixtures.js
o-header-services/demos/src/header.mustache
origami-navigation-service/views/partials/header.html
o-tracking/src/javascript/events/click.js
polyfill-service/src/includes/partials/header.njk
o-toggle/test/toggle.test.js
```

**Comment by nickcolley** [comment]
Had a quick look those other repos seem to encourage the use of `<button>` markup so will focus on a smaller fix for the header component and then we can look broader as necessary later.

**Comment by nickcolley** [comment]
@JakeChampion is there any documentation on how to run o-header locally? I can't see any development documentation.

**Comment by JakeChampion** [comment]
@nickcolley good point about the lack of documentation, we have some on our website but we don't link to it from the readmes, perhaps we should!

https://origami.ft.com/docs/components/contributing/#working-on-a-component

The main workflow is to `npm install origami-build-tools --global` and run `obt dev`
