### ISSUE TITLE
Navigation "burger" not right-aligned on small screens

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/o-header#46]
device_model = iPhone 4 GSM
device_res = 960x640
orientation = portrait OR landscape
os_name = iOS
os_version = 6.1.3
pixel_density = 326 ppi
status = Viewport

![2014-07-09_13 10 53_p_ft prod iphone 4e](https://cloud.githubusercontent.com/assets/7458891/3524027/6a4dbcdc-0762-11e4-8818-6a8de26bd70a.png)

Testing the same page on an iPhone 5, this is not an issue:

device_model = iPhone
device_res = 640x1136
orientation = portrait
os_name = iOS
os_version = 7.1.1
pixel_density = 326 ppi
request_id = AE7808A2-6030-473F-948A-385802900553
status = Viewport

![2014-07-09_13 14 12_p_ft sprod iphone 5cb](https://cloud.githubusercontent.com/assets/7458891/3524046/ada4545a-0762-11e4-959c-52a7a31db472.png)

**Comment by kaelig** [comment]
Could not reproduce in v3.0.0.
