### ISSUE TITLE
Preparing next major release

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-header#61]
There are some issues which would require a new major release, as they would need markup changes:

* Unify .o-ft-header__logo and o.ft-header__logo--ft into one
* Alternative markup so that the brand colour doesn't require linear gradient and will work on IE9 and under
* Maybe stop using own table layout and implement o-grid more
* Implement new markup so that it will be reusable in minimized version
* Fixed header
* Improve flexibility to tools bar. Currently it needs 4 items
* Core experience with links to menu items in footer
* Change h1 tag for titles
* '10 px spacing on the left and right of the "back to" FT square icon.' This needs the class to be applied to the a tag instead of the i tag.

**Comment by kaelig** [comment]
@AlbertoElias can you review this issue and list what is still relevant in the original post so that I can bundle them into the v3?

**Comment by AlbertoElias** [comment]
So in the meeting last week with @danskinner we agreed that, while we're waiting for Next to establish the new design, this needed updating, but we wouldn't fix everything and the two main issues are:

* Improve flexibility to tools bar. Currently it needs 4 items
* Make the whole header smaller so it serves more use cases

All the others, except for fixed header, are still valid as well I'd say.

**Comment by kaelig** [comment]
v3.0.0 has been around for a few weeks now. Closing this.
