### ISSUE TITLE
Add switching between signed in and signed out state

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-header#67]
fastft does it like this http://git.svc.ft.com:8080/projects/FWP/repos/responsive-fastft/browse/client/js/components/signin.js. There's definitely a use case for this across a lot of products, so it could go into o-ft-header

**Comment by kaelig** [comment]
With no update for about 9 months, I'm choosing to close this. We can reopen if it comes up again with the NextFT header.
