### ISSUE TITLE
Back to FT square on the right.

### ISSUE THREAD

**Issue by pauloneillft** [Financial-Times/o-header#75]
Was on the original design mockups. Doesn't seem to be available looking at the "branded" demo on the component page. 

![screen shot 2014-08-11 at 13 00 17](https://cloud.githubusercontent.com/assets/3977053/3875311/cbb0722e-214f-11e4-8e24-296807b83c8c.png)

**Comment by kaelig** [comment]
@pauloneillft and I have looked into this matter and made the necessary spacing tweaks.
