### ISSUE TITLE
Tool icon labels cannot be longer than 8 chars

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-header#83]
This seems really quite limiting:

![image](https://cloud.githubusercontent.com/assets/1735391/4390278/05ef1a5c-43fc-11e4-90dc-ccd08ca0ab98.png)

The Guardian places icon labels to the right, which allows for more flexibility:

![image](https://cloud.githubusercontent.com/assets/1735391/4390296/21128f3a-43fc-11e4-97b9-403d8975fb0a.png)

**Comment by kaelig** [comment]
Because of the way table-cell layout work, we cannot implement this easily to fit all use cases.

Products may override any elements widths themselves with a CSS width targeted at the elements that need a larger width.
