### ISSUE TITLE
Consider removing useragent

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-header#84]
In theme-tools.css:

```
@include oUseragentTarget((ie7, ie8)) {
    .o-ft-header__nav--tools-theme .o-ft-header__back-to-ft {
        filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='#{oFtHeaderAsset('img/ft-logo.png')}',sizingMethod='scale');
    }
}
```

This applies a `filter` property, which is a standard, but sets its value to something in a proprietary Microsoft extension.  It seems wise to avoid other browsers trying to parse this, but isn't there a way to do it across the board with a polyfill rather than having to specify a useragent target for every alpha transparent PNG background?

Eg. http://www.twinhelix.com/css/iepngfix/demo/

It's easier to write and maintain standards compliant code, and easier to integrate origami if you don't have to do UA detection and flagging.  So if there's a polyfill we can put in the polyfill service and remove useragent as a dependency here, we should do that.

**Comment by kaelig** [comment]
oUserAgent has been removed for a while. Closing this.
