### ISSUE TITLE
Header bug on iPhone

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/o-header#89]
Hi,

We are just doing some work on the FT Dev portal and I noticed a couple of glitches on the header on the iPhone. 

In the portrait position the header bar menu takes a longish time to load and when it does the menu and the more button overlap. Also, the position on the screen is slightly skewed. In landscape position the header bar doesn't re-size within the screen. 

Here are some screen to hopefully make more sense...

![photo 1](https://cloud.githubusercontent.com/assets/8235225/4842759/3af5df58-6029-11e4-9f98-cbd0044745d6.PNG)
![photo 2](https://cloud.githubusercontent.com/assets/8235225/4842760/3af8d87a-6029-11e4-85fb-c4849ce0c40f.PNG)

Thanks,
Sarah

**Comment by kaelig** [comment]
Closing, as v3.0.0 fixes this problem
