### ISSUE TITLE
bower: use dom-delegate not ftdomdelegate

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-header#97]
At some point the name changed.

**Comment by kaelig** [comment]
Are you sure? Financial-Times/o-dom-delegate redirects to Financial-Times/ftdomdelegate.

**Comment by kavanagh** [comment]
No I'm not sure. Then I think some other components (not sure which) need to stop using dom-delegate because I have both.

**Comment by kaelig** [comment]
Closing this as it seems unclear. Feel free to reopen if the problem arises again.
