### ISSUE TITLE
Decouple o-hierarchical-nav and o-squishy-list from o-header

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-header#98]
Has any existing use of o-header require the extra size and complexity these two bring?

* hierarchical nav not to great on touch.
* these two bloat this library
* they are useful in kitchen sink use cases.

**Comment by AlbertoElias** [comment]
If we remove the nav, what would we have instead? And o-squishy-list is useful for the responsiveness of the header, and the header in developer.ft.com uses it

**Comment by kavanagh** [comment]
I'm not suggesting your header doesnt have a nav. I mean decoupling the modules to break the dependency.

I didn't realise squishy list is used for responsiveness of the header layout. But perhaps that is something that should either be left to the grid or indeed not use any dependency at all becuase it's not that complex --- the library would be more cohesive without depending on something.

**Comment by kaelig** [comment]
This is related to #78 and we decided not to invest time on fixing these mobile usability limitations for now.

Note that we're very likely to build the Next FT header Origami module independently from these two modules.
